/*
* generated by Xtext
*/
package org.eclipse.cbi.targetplatform;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class TargetPlatformUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipse.cbi.targetplatform.ui.internal.TargetPlatformActivator.getInstance().getInjector("org.eclipse.cbi.targetplatform.TargetPlatform");
	}
	
}
