/*
 * generated by Xtext
 */
package fr.obeo.releng;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TargetPlatformRuntimeModule extends fr.obeo.releng.AbstractTargetPlatformRuntimeModule {

}
