/*
* generated by Xtext
*/
package fr.obeo.releng.targetplatform.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class TargetPlatformOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
