/*
* generated by Xtext
*/
package fr.obeo.releng.ui.contentassist;

import fr.obeo.releng.ui.contentassist.AbstractTargetPlatformProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class TargetPlatformProposalProvider extends AbstractTargetPlatformProposalProvider {

}
