/*
* generated by Xtext
*/
package fr.obeo.releng.targetplatform.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.jface.viewers.StyledString;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import com.google.inject.Inject;

import fr.obeo.releng.targetplatform.targetplatform.IU;
import fr.obeo.releng.targetplatform.targetplatform.Location;
import fr.obeo.releng.targetplatform.targetplatform.TargetPlatform;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class TargetPlatformLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public TargetPlatformLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	Object text(Location object) {
		StyledString ss = new StyledString();
		ss.append(object.getUri());
		if (object.getId() != null) {
			ss.append(" " + object.getId(), StyledString.DECORATIONS_STYLER);
		}
		return ss;
	}
	
	String image(Location object) {
		return "obj16/location_obj.gif";
	}
	
	Object text(IU object) {
		StyledString ss = new StyledString();
		ss.append(object.getID());
		if (object.getVersion() != null) {
			ss.append(" " + object.getVersion(), StyledString.COUNTER_STYLER);
		}
		return ss;
	}
	
	String image(IU object) {
		return "obj16/iu_obj.gif";
	}
	
	Object text(TargetPlatform object) {
		return object.getName();
	}
	
	String image(TargetPlatform object) {
		return "obj16/target_obj.gif";
	}
	
}
