/*
 * generated by Xtext
 */
package fr.obeo.releng.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TargetPlatformUiModule extends fr.obeo.releng.ui.AbstractTargetPlatformUiModule {
	public TargetPlatformUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
