<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="targetplatform"
    nsURI="http://www.obeo.fr/releng/TargetPlatform" nsPrefix="targetplatform">
  <eClassifiers xsi:type="ecore:EClass" name="TargetPlatform">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="locations" upperBound="-1"
        eType="#//Location" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="options" unique="false"
        upperBound="-1" eType="#//Option"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ius" upperBound="-1" eType="#//IU"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Option">
    <eLiterals name="INCLUDE_REQUIRED" literal="requirements"/>
    <eLiterals name="INCLUDE_ALL_ENVIRONMENTS" value="1" literal="allEnvironments"/>
    <eLiterals name="INCLUDE_SOURCE" value="2" literal="source"/>
    <eLiterals name="INCLUDE_CONFIGURE_PHASE" value="3" literal="configurePhase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IU">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
