/**
 * generated by Xtext
 */
package fr.obeo.releng.targetplatform.ui.contentassist;

import fr.obeo.releng.targetplatform.ui.contentassist.AbstractTargetPlatformProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class TargetPlatformProposalProvider extends AbstractTargetPlatformProposalProvider {
}
