/*
 * generated by Xtext 2.11.0
 */
package org.eclipse.cbi.targetplatform.ide;


/**
 * Use this class to register ide components.
 */
public class TargetPlatformIdeModule extends AbstractTargetPlatformIdeModule {
}
